# Numpy #
-  NumPy is a Python library.
-  NumPy is used for working with arrays.
- NumPy is short for "Numerical Python".
- It provides powerful N-dimensional arrays and mathematical functions.
# why  numpy #
- Faster than Python lists
- Memory efficient
- Optimized for numerical and scientific operations


### NumPy as np
- NumPy is usually imported under the np alias.
- alias: In Python alias are an alternate name for referring to the same thing.


In [1]:
import numpy as np 
np.__version__

'2.4.0'

In [2]:
# Python list
lst = [1, 2, 3, 4]
print(lst)


# NumPy array
import numpy as np
arr = np.array([1, 2, 3, 4]) 
print( arr)



[1, 2, 3, 4]
[1 2 3 4]


In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [4]:
lis = [1, 2, 3, "pwskills", 3+5j, True, 1.2] #list stores heterogenous data
type(lis)
print(lis)

[1, 2, 3, 'pwskills', (3+5j), True, 1.2]


In [5]:
# creating array 
import numpy as np 
r= np.array([1,2,3,4,5])
print(r)
print(type(r))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
# Dimension in arrays:
# 0-D array
# 1-D array
# 2-D array
# 3-D array
# higher dimension array:

# 0-D array 
import numpy as np

arr = np.array(42)

print(arr)

42


In [7]:
# 1-D array:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [8]:
# 2-d array:
import numpy as np 
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [9]:
# 3-D array:
import numpy as np 
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)
type(arr)
print(arr.ndim)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [10]:
# check the  number of dimenssions in array :
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])

d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]],[[1,2,3],[6,7,8]]])

print(a)
print(b)
print(c)
print(d)

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [6 7 8]]]
0
1
2
3


In [11]:
import numpy as np 
a= np.array([[[1,2,3,4],[2,3,2,4]],[[12,2,3,33],[12,2,13,43]]])
print(a)

[[[ 1  2  3  4]
  [ 2  3  2  4]]

 [[12  2  3 33]
  [12  2 13 43]]]


In [12]:
import numpy as np 
a= np.array([[[1,2,3,4],[2,3,2,4]],[[12,2,3,33],[12,2,13]]]) # it will throw an error becouse of different number of elements in inner list

print(a)
print(a.ndim)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 2) + inhomogeneous part.

# Higher Dimensional Arrays
- An array can have any number of dimensions.

- When the array is created, you can define the number of dimensions by using the ndmin argument

In [ ]:
# higher dimension array:
import numpy as np 
arr = np.array([1, 2, 3, 4], ndmin=5) #

print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
import numpy as np 
ramesh = np.array([ 1,2,3,4,5],ndmin=  8)
print(ramesh)

[[[[[[[[1 2 3 4 5]]]]]]]]


In [ ]:
import numpy as np 
khushi = np.array([1,2,3,4,5,6,7],ndmin=15)
print(khushi)

[[[[[[[[[[[[[[[1 2 3 4 5 6 7]]]]]]]]]]]]]]]


In [ ]:
# numpy array  
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[3])
print(arr[1])

1
4
2


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])
print(arr[0]+ arr[2])
print(arr[3]+ arr[2])
print(arr[2]+ arr[[2]])
print(arr)
type(arr[2])
type(arr)


7
4
7
[6]
[1 2 3 4]


numpy.ndarray

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4,"ramesh ", 3+5j, True, 1.2,{"key1": "value1", "key2": "value2" ,"key3": "value3" },"khushi"])

print(arr)

[1 2 3 4 'ramesh ' (3+5j) True 1.2
 {'key1': 'value1', 'key2': 'value2', 'key3': 'value3'} 'khushi']


In [ ]:
type(arr)

type(arr[1])
type(arr[2])
type(arr[8])

dict

In [ ]:
# accessing 2-d array 
import numpy as np

arr = np.array([
     [1,2,3,4,5],
     [6,7,8,9,10]
 ])

print(arr)

print('2nd element on 1st row: ', arr[0, 1])
print( arr[0, 1])
print( arr[1, 2])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row:  2
2
8


In [ ]:
# indexing rules :
# array[row, column]
import numpy as np

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr2)
# arr2[1, 2]
arr2[1,1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


np.int64(5)

In [ ]:
arr2[1]

array([4, 5, 6])

In [ ]:
arr2[2]

array([7, 8, 9])

In [ ]:
# 3-D array:
import numpy as np 
arr3 = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])
print(arr3)
type(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


numpy.ndarray

In [ ]:
# # # rules for 3_d array
# # # array[depth, row, column]

# # Block 0
# #   [1 2 3]
# #   [4 5 6]

# # Block 1
# #   [7 8 9]
# #   [10 11 12]

# # (2, 2, 3)

# 2 blocks
# 2 rows
# 3 columns
arr3[0, 1, 2]

np.int64(6)

In [ ]:
print(arr3.ndim)

3


In [ ]:
arr3[0,1,2]

np.int64(6)

In [ ]:
import numpy as np

arr = np.array([

     [[1, 2, 3], 
     [4, 5, 6]],

     [[7, 8, 9],
     [10, 11, 12]],

     [[2,7,8],
      [4,5,8]] 
])

print(arr[0, 1, 2])
print(arr)
print(arr.ndim)

6
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 2  7  8]
  [ 4  5  8]]]
3


In [ ]:
arr[1:-2]
arr[-1:-5]

array([], shape=(0, 2, 3), dtype=int64)

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])


[[2 3 4]
 [7 8 9]]


# NumPy Data Types

### Data Types in Python
- By default Python have these data types:

- strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
- integer - used to represent integer numbers. e.g. -1, -2, -3
- float - used to represent real numbers. e.g. 1.2, 42.42
- boolean - used to represent True or False.
- complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j


# Data Types in NumPy

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [ ]:
#  checking data types :
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [ ]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry']) #  ontaining string data 

print(arr.dtype)

arr1 = np.array([1,2,3,4,5,"ramesh","khushi ",3+3j,15])
print(arr1)
type (arr1)

<U6
['1' '2' '3' '4' '5' 'ramesh' 'khushi ' '(3+3j)' '15']


numpy.ndarray

In [ ]:
type(arr[2])


numpy.str_

In [ ]:
type(arr1[7])

numpy.str_

In [ ]:
type(arr1[8])


numpy.str_

In [ ]:
# Creating Arrays With a Defined Data Type: use the (dtype) that allows us to define the excepted data types 
# For any types : i, u, f, S and U we can define size as well.


import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')
arr0 = np.array([1, 2, 3, 4])
print(arr0)
print(arr)
print(arr.dtype)

[1 2 3 4]
[b'1' b'2' b'3' b'4']
|S1


In [ ]:
arr11 = np.array([1, 2, 3, 4], dtype='i')
print(arr11)
print(arr11.dtype)


[1 2 3 4]
int32


In [ ]:
arr4 = np.array([1, 2, 3, 4], dtype='f')
print(arr4)
arr4.dtype

[1. 2. 3. 4.]


dtype('float32')

In [ ]:
arr4 = np.array([ramesh, 2, 3, 4], dtype='i') # it will throw an errors 
arr4.dtype


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [ ]:
# Converting Data Type on Existing Arrays : ,use the ( astype() )methods  
import numpy as np

array = np.array([1.1, 2.1, 3.1])

newarr = array.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
arr = np.array([1.1, 2.1, 3.1])
new = array.astype('int')
print(new )
new.dtype

[1 2 3]


dtype('int64')

In [ ]:
new1 = array.astype(bool)
print(new1 )
new1.dtype

[ True  True  True]


dtype('bool')

# NumPy Array Copy vs View

## What is View?

- A view does not create new data.
- It references the original array’s memory.

- Modification affects original array.

##  What is Copy?

- A copy creates a completely new memory block.

- Modification does NOT affect original array.

In [ ]:
# copy() → returns copy ,view() → returns view
a = np.array([1, 2, 3, 4])

c = a.copy()

c[0] = 100

print("a:", a) # no change original data 
print("c:", c)  

a: [1 2 3 4]
c: [100   2   3   4]


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])

b = a.view()

b[0] = 100

print("a:", a) # change the original data types :

print("b:", b)

a: [100   2   3   4]
b: [100   2   3   4]


In [ ]:
print(b.base) # no none means - view 

[100   2   3   4]


In [ ]:
print(a.base) # none means - copy :


None


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


# NumPy Array Shape & reshape 

- Shape = structure of array

In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40])
print(a.shape)

(4,)


In [ ]:
b = np.array([[1,2,3],
              [4,5,6]])

print(b.shape)    # (2,3,): - 2 row , 3 col , matrix 2*3 

(2, 3)


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)
print(arr.ndim)



(2, 4)
2


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)   # 1 block , and all bloke inside the block , 4 is number of elements :



[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [ ]:
c = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(c.shape)   
print()
# 2 blocks
# 2 rows
# 2 columns
print(c )



(2, 2, 2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Reshaping arrays: rules - Old size = New size
# Reshape changes the shape (structure) of an array without changing the data.

import numpy as np

a = np.array([1,2,3,4,5,6])

b = a.reshape(2,3)
print(b)
b.dtype

[[1 2 3]
 [4 5 6]]


dtype('int64')

In [ ]:
import numpy as np  # 1d to 2d 

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2) # block,row , col 

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
newarr1 = arr.reshape(3, 2, 2)  
print(newarr1)


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
# what Can We Reshape Into any Shape? no it will throw an errors 

newarr1 = arr.reshape(4, 2, 2)  


ValueError: cannot reshape array of size 12 into shape (4,2,2)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)  # it is view 


[1 2 3 4 5 6 7 8]


# Iteration
 ## iteration means access the elements one by one  is called iteration 
 - use for loop 

In [ ]:
import numpy as np # 1d - array 

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [ ]:
import numpy as np #  2d - array :

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)


[1 2 3]
[4 5 6]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
# 3d - array:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
import numpy as np # iterate

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# itearting array using nditer()
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
import numpy as np # iterate

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in np.nditer(arr):
     print(x)


1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
 # We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements whileiterating.

import numpy as np
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)


np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# Joining means putting contents of two or more arrays in a single array.

# types :
- concatenate()
- stack()
- hstack()
- vstack()
- dstack()

# meaning :

- concatenate	Join on existing axis
- stack:	Add new axis and join
- hstack:	Horizontal join
- vstack:	Vertical join
- dstack:	Depth join

In [ ]:
 # use concatenate
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)


# Axis=0 join ke liye:

# Columns same hone chahiye

# Axis=1 join ke liye:

# Rows same hone chahiye

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


In [ ]:
a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
              [7,8]])

np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
# using stack : - Adds new dimension and stacks arrays.
a = np.array([1,2,3])
b = np.array([4,5,6])

np.stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
z= a,b 
np.stack(z)
print(z)


(array([1, 2, 3]), array([4, 5, 6]))


In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)



[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Stacking Along Rows  , use : hstack() 
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)



[1 2 3 4 5 6]


In [ ]:
# along col , use : - vstack()
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)


[[1 2 3]
 [4 5 6]]


In [ ]:
# dstack() Depth wise (3rd dimension me join)

import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)



[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])
arr3 = np.array([4, 5, 6])
arr4 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2, arr3,arr4))

print(arr)

[[[1 4 4 4]
  [2 5 5 5]
  [3 6 6 6]]]


# Splitting
### Splitting means dividing one array into multiple sub-arrays.


In [ ]:
# use np.split()
import numpy as np

a = np.array([1,2,3,4,5,6])

b = np.split(a, 3)
print(b)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# specific index ;    Note: Similar alternates to vstack() and dstack() are available as vsplit() and dsplit().

np.split(a, [2,4])

[array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)


[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)
print(newarr)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


In [ ]:
newarr = np.array_split(arr, 4)
print(newarr)
print(newarr[1])
print(newarr[2])
print(newarr[3])

[array([1, 2]), array([3, 4]), array([5]), array([6])]
[3 4]
[5]
[6]


In [ ]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
newarr12 = np.array_split(arr, 5)
print(newarr12)
print(newarr[3])



[array([[1, 2],
       [3, 4]]), array([[5, 6]]), array([[7, 8]]), array([[ 9, 10]]), array([[11, 12]])]
[[ 9 10]]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
newarr = np.array_split(arr, 3, axis=0)
print(newarr)



[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
# use hstack()
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
# searching You can search an array for a certain value, and return the indexes that get a match.To search an array, use the where() method.
 # its work on indexinng 

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [ ]:
y=  np.where(arr==2)
print(y)

(array([1]),)


In [ ]:
# use condition 
np.where(arr > 4)

(array([4]),)

In [ ]:
np.where(arr > 3)


(array([3, 4, 5, 6]),)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0) # even number 

print(x)

(array([1, 3, 5, 7]),)


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1) # odd  numbers 

print(x)

(array([0, 2, 4, 6]),)


In [ ]:
# # Search Sorted:
# np.searchsorted()

# Finds insertion position in sorted array.

#  np.argwhere()

# Returns coordinates of elements satisfying condition.

#  np.nonzero()

# Returns indices of non-zero elements.

#  argmax() / argmin()

# Returns index of max/min element.

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)
print(x)
print(arr)

In [14]:
x = np.searchsorted(arr, 7)
print(x)

1


In [13]:
x = np.searchsorted(arr, 10)
print(x)

4


In [12]:
x = np.searchsorted(arr, 5)
print(x)

0


In [5]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 3, side='right')

print(x)

0


In [3]:
a = np.array([10,20,30,40])

np.searchsorted(a, 25)

np.int64(2)

In [4]:
np.searchsorted(a, 32)


np.int64(3)

In [6]:
np.searchsorted(a, 5)


np.int64(0)

In [3]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='left')

print(x)

1


In [4]:
# passs multivalues :
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [ ]:
a = np.array([0,1,0,2,3]) # provides nonzero elements index :

np.nonzero(a)

(array([1, 3, 4]),)

In [8]:
a = np.array([10,50,20,5])

print(np.argmax(a))  # 1
print(np.argmin(a))  # 3

1
3


In [13]:
a = np.array([10,50,20,5,45,60,70,80,90,40,10])
print(np.argmax(a))    # return maximum and minimum value index :
print(np.argmin(a))

8
3


In [15]:
# sort :
#  Sorting arranges array elements in order (ascending or descending).

import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [ ]:
# string 

import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [19]:
# bool 

import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [20]:
# 2-d array:

import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
np.sort(arr[::-1]) # decending 

array([[0, 1, 5],
       [2, 3, 4]])

In [ ]:
np.sort(arr[-2::])  # top  value 


array([[2, 3, 4],
       [0, 1, 5]])

# Filtering Arrays


In [23]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [25]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])

result = a[a > 25]  #  follow bool condition  , True , False
print(result)

[30 40 50]


In [27]:
a[(a > 15) & (a < 45)] # multiple condition 

array([20, 30, 40])

In [29]:
a[(a > 15) | (a < 45)]

array([10, 20, 30, 40, 50])

In [35]:
d=a[a > 25] = 100
print(d)

100


In [30]:
b = np.array([[1,2,3],
              [4,5,6]])

b[b > 3]

array([4, 5, 6])

In [36]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False, False, True, True]
[43 44]


In [39]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []
for element in arr:
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [40]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [41]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


# Random numbers:
### it is generate the random numbers
- its different types 

In [1]:
# random int :
# use randint 
from numpy import random

x = random.randint(100)

print(x)

51


In [2]:
import numpy as np

np.random.randint(1, 10)

3

In [7]:
np.random.randint(1, 10, size=5)  # with size 

array([6, 9, 1, 7, 4], dtype=int32)

In [4]:
# genrate float:
# use rand()

In [5]:
from numpy import random

x = random.rand()

print(x)

0.1570907631456101


In [6]:
np.random.rand(3)

array([0.80893932, 0.56496006, 0.3611146 ])

In [10]:
np.random.rand(5,10)

array([[0.26038692, 0.01011098, 0.64627596, 0.16232315, 0.88716425,
        0.5825701 , 0.25037074, 0.57786812, 0.21295038, 0.41027572],
       [0.49466172, 0.47078125, 0.19037417, 0.20565719, 0.99357017,
        0.22945684, 0.86022551, 0.279434  , 0.60182963, 0.81270794],
       [0.25827401, 0.49666273, 0.47942209, 0.56130625, 0.99918703,
        0.13741019, 0.89435404, 0.53741039, 0.737337  , 0.49049798],
       [0.54478544, 0.06520834, 0.14607846, 0.01976248, 0.26736871,
        0.59532576, 0.97677316, 0.07096279, 0.57151173, 0.42852674],
       [0.13845844, 0.57336561, 0.24174926, 0.49702932, 0.37122514,
        0.59022141, 0.855644  , 0.65858762, 0.8542142 , 0.59069279]])

In [11]:
np.random.rand(4,3,4)


array([[[0.57413348, 0.40107212, 0.08245074, 0.16419731],
        [0.77916412, 0.68475215, 0.84376104, 0.06906044],
        [0.95073775, 0.16392207, 0.39480355, 0.98738061]],

       [[0.58148267, 0.17807159, 0.86729905, 0.5226171 ],
        [0.57226154, 0.6381982 , 0.81398662, 0.20231216],
        [0.09824918, 0.96352119, 0.98141613, 0.52398384]],

       [[0.30617007, 0.83915273, 0.13177516, 0.31648253],
        [0.20888018, 0.8512848 , 0.6520752 , 0.30602505],
        [0.30512489, 0.34116321, 0.42414295, 0.28490055]],

       [[0.49626937, 0.17373795, 0.47666107, 0.08792235],
        [0.06698315, 0.40799255, 0.23085193, 0.60058344],
        [0.81177831, 0.25431309, 0.67006824, 0.99787517]]])

In [8]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[16  8 36 55 39]
 [32 82 17  2 98]
 [21 92 56 15 50]]


In [9]:
from numpy import random

x = random.randint(100, size=(10,40))

print(x)

[[24  5 93 15 55  2 32 41 38 90 83 48 83 25  7 98 90 48 70 57 51 44 91 37
  46 14 32 25 66 87 77 44 57 20 50 49 12  3 54  6]
 [10  4 53 16 53 78 63 53  2 74 91 51 66 50 10 38 49 57 30 69 20 55 16 42
  81 83 66 15 97 22 91 28 49 54 14 27 49 88  0 60]
 [36 93  8 92 89 24 56 89 96 97 73 17 39 32  2 29 23 94 81 43 31 56 96  2
  22 56 37 35 36  5 21 77 43 86 69 62 41 49 91 79]
 [56 52 11 92 77 68 20 47 43 33 49 69 49 13  6 91 29 80  8 32 74 93 11 60
  63 11  8 84 57 63 85 43  8 91 71 72  6 80 69 77]
 [69 95 94 87 64 78 64 41 53 78 57 95  9 12 26 56 60 59 40  3 53 71 83 51
  82 20 32 75 78 62  7 92 16 39 39 50 85 60 94 89]
 [63 86 21  1 62 91 57 35 38 21 58 92 75 91 43  6 19 21  1 32 77 23  0 65
  62 39  0 30 88 66 21  6 15 95 47 72 27  0 72 42]
 [90 96 39 23  0 86 92 78 81 98 78 74 39 10 61 84 10  4 68 35 25 61 61 40
  65  6 10 22 14 30 63 64 51 62  3 63  3 15 97 52]
 [24 42 71 96 35 75 56 56  3 19  1 30 50 90 57 92 51 32 65 21 49 74 42 22
  91 30 29 71 88  1 87 17 93 87 33 40 72 98 10 79]


In [12]:
# choice (random section )
a = np.array([10,20,30,40])

np.random.choice(a)

np.int64(40)

In [14]:
np.random.choice(a, size=2)

array([40, 20])

In [16]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5)) # wiht size 

print(x)

[[5 7 7 9 7]
 [5 7 7 5 7]
 [5 5 7 7 9]]


In [19]:
# data distribution : This is very important in statistics and data science because it helps us understand the pattern of data.The random module provides methods that can generate different types of data distributions (like normal distribution, uniform distribution, etc.).
# A random distribution is a set of random numbers that follow a certain probability density function.
# We can generate random numbers based on defined probabilities using the choice() method of the random module.
# The choice() method allows us to specify the probability for each value.

from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)


[7 7 5 7 7 7 5 5 3 7 3 7 7 5 7 7 3 7 5 7 5 7 7 5 7 7 5 5 5 7 7 7 7 7 5 3 7
 7 5 5 7 7 5 5 7 7 7 5 5 7 5 5 7 3 7 5 7 7 7 7 5 7 5 7 5 7 3 5 7 5 7 7 7 7
 7 3 3 5 5 5 5 7 5 7 7 7 7 5 7 7 7 7 7 7 7 7 7 5 7 5]


In [20]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(50))


In [21]:
x

array([5, 7, 7, 7, 7, 7, 3, 7, 7, 7, 7, 7, 5, 5, 3, 7, 7, 5, 7, 3, 5, 7,
       7, 7, 5, 7, 7, 7, 3, 3, 3, 7, 7, 7, 5, 5, 7, 7, 5, 3, 7, 5, 7, 5,
       7, 7, 7, 5, 7, 5])

In [46]:
# Shuffling Arrays
# Shuffle means changing arrangement of elements in-place. i.e. in the array itself.
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr) #The shuffle() method makes changes to the original array.



[1 4 3 5 2]


In [51]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))

[4 5 1 3 2]


In [52]:
# numpy universal functions (ufuncs):  Work element-wise ,  its like boardcasting 
# What is Vectorization?
# Converting iterative statements into a vector based operation is called vectorization.
# It is the process of applying operations to entire arrays at once instead of processing one element at a time.

# without vectorizations 
import numpy as np

a = np.array([1,2,3,4])
result = []

for i in a:
    result.append(i * 2)

print(result) 

[np.int64(2), np.int64(4), np.int64(6), np.int64(8)]


In [53]:
a = np.array([1,2,3,4])
result = a * 2
print(result)

[2 4 6 8]


In [54]:
# without ufunc be can use built in zip() method use 
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


In [56]:
# with ufunc :  add()
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]    # it work an elements wised 
z = np.add(x, y)

print(z)

[ 5  7  9 11]


In [ ]:
# create an own ufunc :
import numpy as np
 # use func :
 
def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))


[6 8 10 12]


In [58]:
print(type(np.add))

<class 'numpy.ufunc'>


In [60]:
if type(np.add) == np.ufunc:
  print('add is ufunc')
else:
  print('add is not ufunc')


add is ufunc


In [3]:
# simple  Arithmetics
# Add ()
import numpy as np

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


In [4]:
# subtract

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)


[-10  -1   8  17  26  35]


In [5]:
# multiply 


arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)


[ 200  420  660  920 1200 1500]


In [6]:
# division

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.divide(arr1, arr2)

print(newarr)


[0.5        0.95238095 1.36363636 1.73913043 2.08333333 2.4       ]


In [7]:
# power()
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[         1000       3200000     729000000 6553600000000          2500
             0]


In [8]:
# mode 
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [11]:
arr1 = np.array([54, 10, 850, 740, 140, 0.160]) # return raminder 
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)

print(newarr)

[0.   3.   4.   4.   0.   0.16]


In [13]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])               # mode , remainder  sane ass 

newarr = np.remainder(arr1, arr2)

print(newarr)


[ 1  6  3  0  0 27]


In [ ]:
# quotient and mode : The divmod() function return both the quotient and the mod. T
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [ ]:
# #  use absolute :Absolute value returns the distance from zero, ignoring the sign.

# import numpy as np

# arr = np.array([-1, -2, 1, 2, 3, -4])

# newarr = np.absolute(arr)

# print(newarr)



[1 2 1 2 3 4]


In [16]:
# # rounding decimals : 

# There are primarily five ways of rounding off decimals in NumPy:

# truncation
# fix
# rounding
# floor
#  ceil

# 1 Truncation
# Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.
import numpy as np

arr = np.trunc([-3.1666, 3.6667])

print(arr)





[-3.  3.]


In [18]:
arr = np.fix([-3.1666, 3.6667])
arr = np.fix([-3.1666, -3.6667])

print(arr)

[-3. -3.]


In [19]:
arr = np.fix([-3.1666, 0.6667])

print(arr)

[-3.  0.]


In [20]:
# 2 Rounding  :
import numpy as np

arr = np.around(3.1666)

print(arr)

3.0


In [21]:
import numpy as np

arr = np.around(3.1666, 2)

print(arr)

3.17


In [28]:
import numpy as np

arr = np.around(3)

print(arr)

3


In [29]:
# floor : The floor() function rounds off decimal to nearest lower integer.
import numpy as np

arr = np.floor([-3.1666, 3.6667])

print(arr)

[-4.  3.]


In [30]:
# ceil:  rounds off decimal to nearest upper integer.
arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  4.]


In [34]:
# log function : find base e :

import numpy as np

arr = np.arange(1, 10)

print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [35]:
import numpy as np

arr = np.arange(1, 10)

print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [36]:
import numpy as np

arr = np.arange(1, 10)

print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [38]:
import numpy as np

arr = np.array([1, 10])

print(np.log2(arr))

[0.         3.32192809]


In [ ]:
# at log any base :   numpy does not provide any functions , be can use inbuilt function math.log()
from math import log

import numpy as np

nplog = np.frompyfunc(log, 2, 1)

print(nplog(100, 15))

1.7005483074552052


In [40]:
# summations :
# What is the difference between summation and addition?
# Addition in NumPy performs element-wise addition.
# Summation returns the total of array elements.

In [41]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)


[2 4 6]


In [42]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

12


In [43]:
# Summation Over an Axis
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


In [47]:
# Cummulative Sum
# Cummulative sum means partially adding the elements in array.

# E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].

# Perfom partial sum with the cumsum() function.
arr = np.array([1, 2, 3])

newarr = np.cumsum(arr)

print(newarr)


[1 3 6]


In [51]:
import numpy as np
arr222 = np.array([1, 2, 3,25])
newarr1 = np.cumsum(arr222)
print(arr222)
print(newarr1)


[ 1  2  3 25]
[ 1  3  6 31]


In [52]:
# product : Product means multiplying values together.
# use prod()
import numpy as np

arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)



24


In [53]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])

print(x)

40320


In [54]:
# over an exis =1 ,0
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

[  24 1680]


In [55]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=0)

print(newarr)

[ 5 12 21 32]


In [57]:
# Cummulative product means taking the product partially.

# E.g. The partial product of [1, 2, 3, 4] is [1, 1*2, 1*2*3, 1*2*3*4] = [1, 2, 6, 24] , use cumprod()


arr = np.array([5, 6, 7, 8]) # 

newarr = np.cumprod(arr)

print(newarr)


[   5   30  210 1680]


In [59]:
# Differences
# A discrete difference means subtracting two successive elements.

# E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

# To find the discrete difference, use the diff() function.

import numpy as np

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr)

print(newarr)

[  5  10 -20]


In [60]:
import numpy as np

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr, n=2)

print(newarr)

[  5 -30]


In [62]:
import numpy as np

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr, n=1)

print(newarr)

[  5  10 -20]


In [63]:
# LCM Lowest Common Multiple
# The Lowest Common Multiple is the smallest number that is a common multiple of two numbers
import numpy as np

num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)


12


In [ ]:
# finding LCM in array using reduce() method 


import numpy as np

arr = np.array([3, 6, 9])

x = np.lcm.reduce(arr)

print(x)

18


In [67]:
import numpy as np

arr = np.arange(1, 11)

x = np.lcm.reduce(arr)

print(x)

2520


In [69]:
# NumPy GCD Greatest Common Divisor:  GCD is the largest number that divides both numbers without remainder.
# use built in gcd()
import numpy as np

num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)

3


In [70]:
# use in array :   be can use reduce()method 
import numpy as np

arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)


4


In [71]:
# Trigonometric Functions
# NumPy provides the ufuncs sin(), cos() and tan() that take values in radians and produce the corresponding sin, cos and tan values.
# Trigonometric functions relate angles to ratios of sides in a triangle.
# find  value PI/2 
import numpy as np

x = np.sin(np.pi/2)

print(x)

1.0


In [72]:
# in array :
import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sin(arr)

print(x)

[1.         0.8660254  0.70710678 0.58778525]


In [ ]:
# Convert Degrees Into Radians  : Note: radians values are pi/180 * degree_values.
import numpy as np

arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [74]:
# Radians to Degrees
import numpy as np

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


In [ ]:

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi,3*np.pi,8*np.pi])

x = np.rad2deg(arr)

print(x)

[  90.  180.  270.  360.  540. 1440.]


In [77]:
# # Finding Angles: -Finding angles means using inverse trigonometric functions to calculate the angle from a given sine, cosine, or tangent value.

# Function	: Meaning
# np.arcsin()	sin⁻¹
# np.arccos()	cos⁻¹
# np.arctan()	tan⁻¹

import numpy as np

x = np.arcsin(1.0)

print(x)

1.5707963267948966


In [78]:
import numpy as np

arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)

[ 1.57079633 -1.57079633  0.10016742]


In [81]:
import numpy as np

arr = np.array([1, -1, 0.1])

x = np.arccos(arr)

print(x)

[0.         3.14159265 1.47062891]


In [83]:
import numpy as np

arr = np.array([2, -1, 0.1])

x = np.arctan(arr)

print(x)

[ 1.10714872 -0.78539816  0.09966865]


In [84]:
# Hypotenues:
#  NumPy provides the hypot() function that takes the base and perpendicular values and produces hypotenues based on pythagoras theorem.

In [85]:
import numpy as np

base = 3
perp = 4

x = np.hypot(base, perp)

print(x)

5.0


In [86]:
import numpy as np

base = 3.1
perp = 40

x = np.hypot(base, perp)

print(x)

40.119945164469


In [87]:
# # Hyperbolic function
# # Hyperbolic functions are similar to trigonometric functions but are based on hyperbolas instead of circles.

# Function	Meaning
# np.sinh()	Hyperbolic sine
# np.cosh()	Hyperbolic cosine
# np.tanh()	Hyperbolic tangent

import numpy as np

x = np.sinh(np.pi/2)

print(x)

2.3012989023072947


In [88]:
import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.cosh(arr)

print(x)

[2.50917848 1.60028686 1.32460909 1.20397209]


In [89]:
#Finding Angles
# arcsinh(), arccosh() and arctanh() that produce radian values for corresponding sinh, cosh and tanh values
import numpy as np

x = np.arcsinh(1.0)

print(x)

0.881373587019543


In [90]:
import numpy as np

arr = np.array([0.1, 0.2, 0.5])

x = np.arctanh(arr)

print(x)

[0.10033535 0.20273255 0.54930614]


In [92]:
# Set operations :
# Set operations allow you to perform mathematical set logic like union, intersection, difference, and unique on arrays.


import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7]) # unique remove the duplicate values 

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


In [4]:
#Finding Union
# To find the unique values of two arrays, use the union1d() method. (  sub unique values )

import numpy as np

arr1 = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
arr2 = np.array([1, 1, 4, 2, 3, 4, 5, 5, 8, 7])

x = np.union1d(arr1,arr2)

print(x)

[1 2 3 4 5 6 7 8]


In [ ]:
# use the intersect1d() method.

import numpy as np

a = np.array([1,2,3,4])
b = np.array([3,4,5,6])

In [ ]:
np.intersect1d(a, b)  # dono me jo comon hoga ok  

array([3, 4])

In [ ]:
# To find only the values in the first set that is NOT present in the seconds set, use the setdiff1d() method.
np.setdiff1d(a, b) # A me jo hai but B me nahi hai

array([1, 2])

In [11]:
# Symmetric Difference:
#  To find only the values that are NOT present in BOTH sets, use the setxor1d() method.
np.setxor1d(a, b) # np.setxor1d(a, b)

array([1, 2, 5, 6])