In [1]:
import  numpy as np 
x= np.array([8,2,5,3,5])
print(x)
type(x)
print (x.ndim)



[8 2 5 3 5]
1


In [2]:
w= ([1,5,8,9,6])
print(w)
type(w)

[1, 5, 8, 9, 6]


list

In [4]:
#creatinf arrays...>>>> use np.array()
import numpy as np
a= [2,3,4,5]
y= np.array(x)
print(y)
print ()

import numpy as np
a= [2,3,4,5]
y= np.array([2,4,5,6,6])
print (y)
print(y.ndim)


[1 2 5 3 5]

[2 4 5 6 6]
1


In [4]:
import numpy as np
a= [2,3,4,5]
y= np.array([2,4,5,6,6])
y #.... whne check the array tahn type  only variable ( y )


array([2, 4, 5, 6, 6])

In [5]:
print( type(y)) #  use this 

<class 'numpy.ndarray'>


In [ ]:
l=[]
for i in range (1,10):
    int_1 = input("enter :") # when int function is not use then  it providde as a strings in outputs 
    l.append(int_1)
    print(np.array(l))

enter : 4


['4']


enter : 8


['4' '8']


enter : 6


['4' '8' '6']


enter : 2


['4' '8' '6' '2']


enter : 3


['4' '8' '6' '2' '3']


enter : 8


['4' '8' '6' '2' '3' '8']


enter : 8


['4' '8' '6' '2' '3' '8' '8']


enter : 5


['4' '8' '6' '2' '3' '8' '8' '5']


In [6]:
l=[]
for i in range (1,10):
    int_1 = int(input("enter :")) # when use int fun , then  genrate output only array list 

    l.append(int_1)
    print(np.array(l))
    

enter : 8


[8]


enter : 5


[8 5]


enter : 5


[8 5 5]


enter : 6


[8 5 5 6]


enter : 8


[8 5 5 6 8]


enter : 9


[8 5 5 6 8 9]


enter : 8


[8 5 5 6 8 9 8]


enter : 5


[8 5 5 6 8 9 8 5]


enter : 6


[8 5 5 6 8 9 8 5 6]


In [6]:
 ar2 = np.array ([[1,2,3,4,5] , [1,2,3,4,5]])
print(ar2)
print(ar2.ndim )

[[1 2 3 4 5]
 [1 2 3 4 5]]
2


In [9]:
 ar2 = np.array ([[1,2,3,4,6,] , [1,2,3,4]]) # array element is not sem  in dimensions 
print(ar2)
print(ar2.ndim )

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [14]:
 ar3 = np.array ([[[1,2,3,4,6,] , [1,2,3,4,8] ,[4,5,6,3,1]]]) 
print (ar3)
print(ar3.ndim )

[[[1 2 3 4 6]
  [1 2 3 4 8]
  [4 5 6 3 1]]]
3


In [18]:
ary = np.array([4,8,9,5] , ndmin = 10)
print (ary)
print (ary.ndim )

[[[[[[[[[[4 8 9 5]]]]]]]]]]
10


In [19]:
import numpy as np # >>>>>>>> use tuple to create a numpy array

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [24]:
 # 0 dimensions  array 
import  numpy as np
arr = np.array(42)
print (arr)
type(arr)


42


numpy.ndarray

In [30]:
import numpy as np

x = np.array(42) # 0 dimensions 
y = np.array([1, 2, 3, 4, 5]) #>>> 1dimensions 
z = np.array([[1, 2, 3], [4, 5, 6]]) #>>> 2dimensions 
a = np.array([[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]])#>>>3 dimensions 
print (x)
print ()

print (y)
print()

print (z)
print()
print (a)

print(x.ndim)
print(y.ndim)
print(z.ndim)
print(a.ndim)


42

[1 2 3 4 5]

[[1 2 3]
 [4 5 6]]

[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]
0
1
2
3


In [33]:
import  numpy as np 
rr = np.array ( [ 1,2,3,4,5,] , ndmin = 10)
print (rr)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]


In [39]:
 # array numpay indexing ......
# >>> indexing in numpy start with 0 ,  means that first element is 0 and second index is 1 
import  numpy as np 
arr = np.array([1,2,3,4 ,2 ,45,67,9])
print (arr)
print (arr[0])  # get the first element  in array 
print (arr[1])
print (arr[2])
print (arr[5])

[ 1  2  3  4  2 45 67  9]
1
2
3
45


In [40]:
import  numpy as np 
arr = np.array([1,2,3,4 ,2 ,45,67,9])
print (arr)
print (arr[1])  # get the second element in array 


[ 1  2  3  4  2 45 67  9]
2


In [46]:
 import numpy as np 
rr = np.array([1,2,3,4,5,4,3])
print(rr)
print (rr[1] + rr[3] + [5])
print (rr[0])
print (rr[1])
print (rr[3])
print (rr[5])

[1 2 3 4 5 4 3]
[11]
1
2
4
4


In [1]:
 # 2D array .>>>> to access element  from 2-D arrys we can use comma seperated  integers reperesenting the dimension   ans index  of elements 
import  numpy as np 
rr =np.array([[1,2,35,4,52,] , [1,2,3,4,5]])
print (rr[1,4])
print (rr)


5
[[ 1  2 35  4 52]
 [ 1  2  3  4  5]]


In [5]:
import numpy as np 
aa = np.array([[1,2,3,4 ,45 ,87,57,40,54,85] ,[3,4,37,5 ,87,41,54,85,98,80 ] ,[3,5,8,77,85,87,10,32,52,10]])
print (aa)
print (aa [2,5])

[[ 1  2  3  4 45 87 57 40 54 85]
 [ 3  4 37  5 87 41 54 85 98 80]
 [ 3  5  8 77 85 87 10 32 52 10]]
87


In [10]:
import numpy as np 
aa = np.array([[1,2,3,4 ,45 ,87,57,40,54,85] ,[3,4,37,5 ,87,41,54,85,98,80 ] ,[3,5,8,77,85,87,10,32,52,10]])
print (aa)
print (aa [2,5])
print (aa[1,5])
print (aa[1,])
print (aa[1,5])
print (aa[2,2])

[[ 1  2  3  4 45 87 57 40 54 85]
 [ 3  4 37  5 87 41 54 85 98 80]
 [ 3  5  8 77 85 87 10 32 52 10]]
87
41
[ 3  4 37  5 87 41 54 85 98 80]
41
8


In [10]:
import numpy as np 
ss = np.array([[[[[1,23,4,54,5,5,66,8,9,8,996,5,54,4] , [1,78,4,75,5,85,8,9,78,996,5,54,42 ,111] , [2,23,4,50,5,79,66,21,12,8,996,30,54,40 ] , [14,23,50,54,90,5,66,8,9,8,996,70,54,11] ,[7,23,40,54,80,40,66,33,44,77,996,88,54,220]]]]])
print (ss)
type(ss)
print (ss[1:3] ,[4,2])
print (ss[3:])



[[[[[  1  23   4  54   5   5  66   8   9   8 996   5  54   4]
    [  1  78   4  75   5  85   8   9  78 996   5  54  42 111]
    [  2  23   4  50   5  79  66  21  12   8 996  30  54  40]
    [ 14  23  50  54  90   5  66   8   9   8 996  70  54  11]
    [  7  23  40  54  80  40  66  33  44  77 996  88  54 220]]]]]
[] [4, 2]
[]


In [9]:
import numpy as np 
ss = np.array([1,23,4,54,5,5,66,8,9,8,996,5,54,4])
print (ss)
print (ss [5:])

[  1  23   4  54   5   5  66   8   9   8 996   5  54   4]
[  5  66   8   9   8 996   5  54   4]


In [13]:
import numpy as np 
ss = np.array([1,23,4,54,5,5,66,8,9,8,996,5,54,4])
print (ss)
print (ss [ -2:-1]) # negative slicing 

[  1  23   4  54   5   5  66   8   9   8 996   5  54   4]
[54]


In [16]:
 # STEP ..>>>>     us ethe step valaue to determine the step of teh slicing 
import numpy as np 
dd = np.array([2,3,4,5,3,55,6,66,77,88,2.2,23.00,00])
print (dd)
print (dd[ 1:9:3])

[ 2.   3.   4.   5.   3.  55.   6.  66.  77.  88.   2.2 23.   0. ]
[ 3.  3. 66.]


In [22]:
import numpy as np 
xxx= np.array([2,3,4,5,3,55,6,66,77,88,2.2,23.00,00] , ndmin =50)
print ( type(xxx))
print (xxx)
print (xxx[::5]) # return  every other element from the entire array 


<class 'numpy.ndarray'>
[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ 2.
                                                   3.
                                                   4.
                                                   5.
                                                   3.
                                                  55.
                                                   6.
                                                  66.
                                                  77.
                                                  88.
                                                   2.2
                                                  23.
                                                   0. ]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ 2.
                                                   3.
                                                   4.
                                                   5.
      

In [6]:
# 2-D array  slicing 
import numpy as np 
zz = np.array([[1,2,3,4,5,6,7] ,[2,3,44,55,66,77,88]])  #from the seconde  element , slice  element from index 1 to index 4 not included:
print (zz)
print (zz[ 1,2:3])
print (zz[ 1,2:5])
print (zz[ 1,4:3])


[[ 1  2  3  4  5  6  7]
 [ 2  3 44 55 66 77 88]]
[44]
[44 55 66]
[]


In [2]:
import numpy as np 
zz = np.array([[1,2,3,4,5,6,7] ,[2,3,44,55,66,77,88]]) 
print (zz)
print (zz[ 1:3,2])
print (zz[ 1,2:5])
print (zz [1,3:4])


[[ 1  2  3  4  5  6  7]
 [ 2  3 44 55 66 77 88]]
[44]
[44 55 66]
[55]


In [3]:
import numpy as np 
zz = np.array([[1,2,3,4,5,6,7] ,[2,3,44,55,66,77,88]])  #from the seconde  element , slice  element from index 1 to index 4 not included:
print (zz)
print (zz[ 1,2:3])
print (zz[0:1 ,1:3])

[[ 1  2  3  4  5  6  7]
 [ 2  3 44 55 66 77 88]]
[44]
[[2 3]]


In [4]:
import numpy as np 
rr= np.array([ 1,2,3] )
print (rr)
print (rr.dtype)

[1 2 3]
int64


In [13]:
import numpy as np 
rr= np.array( [ "banana","mango", "orange " , " rameshkumar "] )  # 
print (rr)
print (rr.dtype)

['banana' 'mango' 'orange ' ' rameshkumar ']
<U13


In [12]:
import numpy as np 
rr= np.array( [ "banana","rameshsunny" ] )
print (rr)
print (rr.dtype)

['banana' 'rameshsunny']
<U11


In [20]:
import numpy as np 
rr= np.array( [ "banana","rameshsunny" ])
print (rr)
print(rr.dtype)

['banana' 'rameshsunny']
<U11


In [21]:
import numpy as np 
arr = np.array([ 1,2,3,4,5])
print (arr)
print (arr.dtype)

[1 2 3 4 5]
int64


In [22]:
import numpy as np 
arr = np.array([ 1.00,2.11,3,4,5])
print (arr)
print (arr.dtype)

[1.   2.11 3.   4.   5.  ]
float64


In [23]:
import numpy as np 
arr = np.array([ 1101,110,11101,])
print (arr)
print (arr.dtype)

[ 1101   110 11101]
int64


In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='f')
print(arr)
print(arr.dtype)


[1. 2. 3. 4.]
float32


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i8')   # when choes the byte and then these are genreate the integer value 

print(arr)
print(arr.dtype)


[1 2 3 4]
int64


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S') # string data type  

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [11]:
import numpy as np

arr = np.array(["ramesh","kumar","janu","sunny"])

print(arr)
print(arr.dtype)

['ramesh' 'kumar' 'janu' 'sunny']
<U6


In [15]:
  # what a value can note be converted >>>>>>>
#    ValueError: >>>>>>>> In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect. 


import numpy as np 

arr = np.array(['a', '2', '3'], dtype='i')  #  a non integer string like a  can  not be convert to the integer than it return the error 

ValueError: invalid literal for int() with base 10: 'a'

In [8]:
# change data type from float to integer by using (i) as a parameter values 


import numpy as np 
aa= np.array([ 1.1, 2.3, 5.3, 3.4])
print( aa)
newaa = aa.astype('i')
print (newaa)
print (newaa.dtype)




[1.1 2.3 5.3 3.4]
[1 2 5 3]
int32


In [5]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1, 1.2])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)


[1 2 3 1]
int32


In [14]:
#change data type  from integer value to boolean values 
import numpy as np

arr = np.array([1.1, 2.1, 3.1, 1.2 ,0 , -3 , 0.0])

newarr = arr.astype('bool')

print(newarr)
print(newarr.dtype)


[ True  True  True  True False  True False]
bool


In [1]:
 #COPY: >>>>   ..........................copy() ..............................
# copy() function use in np.array , The view SHOULD be affected by the changes made to the original array.
#Make a copy, change the original array, and display both arrays:
import numpy as np 
xxx= np.array([1,2,3,4,5,6])
a= xxx.copy()
xxx[0] = 41
print (xxx)
print (a)


[41  2  3  4  5  6]
[1 2 3 4 5 6]


In [4]:
#Make a copy, change the original array, and display both arrays:
import numpy as np

a = np.array([[10, 20], [30, 40]])
b = a.copy()

b[1][1] = 999

print(a)
print()
print(b)


[[10 20]
 [30 40]]

[[ 10  20]
 [ 30 999]]


In [6]:
a = np.array([[10, 20], [30, 40]])
b = a     

b[0][0] = 500

print("Original (a):\n", a)
print()
print("Same (b):\n", b)


Original (a):
 [[500  20]
 [ 30  40]]

Same (b):
 [[500  20]
 [ 30  40]]


In [5]:
#Make a copy, change the original array, and display both arrays:
import numpy as np 
ss= np.array([[ 1,2,3,4,5,6,7] , [55,44,22,11,77,88,99]])
b= ss.copy()
b[1]=5000
print (ss)
print (b)

[[ 1  2  3  4  5  6  7]
 [55 44 22 11 77 88 99]]
[[   1    2    3    4    5    6    7]
 [5000 5000 5000 5000 5000 5000 5000]]


In [6]:
  #VIEW::>>>> >>>>>>>>>>  view()  does not own data  and any changes made to the view will effect the original array , 
# any change made to the original array will effect the view 
import numpy as np 
ss= np.array([[ 1,2,3,4,5,6,7] , [55,44,22,11,77,88,99]])
b= ss.view()
b[1]=5000
print (ss)
print (b)

[[   1    2    3    4    5    6    7]
 [5000 5000 5000 5000 5000 5000 5000]]
[[   1    2    3    4    5    6    7]
 [5000 5000 5000 5000 5000 5000 5000]]


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 422222

print(arr)
print(x)


[422222      2      3      4      5]
[422222      2      3      4      5]


In [12]:
 # check if array owns its data >>>>>>>>>>>>>>>>>>>>
#As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

#Print the value of the base attribute to check if an array owns it's data or not:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
x[1]=9000
y[0]=50000
print(x)
print (y)
print ()

y = arr.view()

print(x.base)
print(y.base)


[   1 9000    3    4    5]
[50000     2     3     4     5]

None
[1 2 3 4 5]


In [19]:
#Print the value of the base attribute to check if an array owns it's data or not:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
x[0]=222
print ()
y = arr.view()
y[1]=8000
print ()

print(x.base)
print(y.base)

#array.base is None → Array apna data rakhta hai.

#array.base is not None → Array kisi aur ka data use kar raha hai.




None
[   1 8000    3    4    5]


In [3]:
import numpy as np

a = np.array([10, 20, 30])
b = a.view()
c = a.copy()

print("a.base:", a.base)   # None
print("b.base:", b.base)   # a
print("c.base:", c.base)   # None
print(a.shape)

a.base: None
b.base: [10 20 30]
c.base: None
(3,)


In [1]:
# 1-D array >>>>
import numpy as np 
array = np.array([1,2,3,4,5]) # 5  1 row with 5 element 
print ( array.shape)

(5,)


In [5]:
import numpy as np

# 1D array
arr1 = np.array([1, 2, 3, 4])
print(arr1.shape)   # Output: (4,) → 1 row with 4 elements

# 2D array
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(arr2.shape)   # Output: (2, 3) → 2 rows and 3 columns

# 3D array
arr3 = np.array([[[1, 2], [3, 4]],[[5, 6],[7, 8]]])

print(arr3.shape)   # Output: (2, 2, 2) → 2 blocks, each with 2 rows and 2 columns

# why use>>>>> 
#It helps you understand the structure of the data.

#Required for matrix operations, reshaping, broadcasting, etc.

#Useful for debugging when shapes don't match.


(4,)
(2, 3)
(2, 2, 2)


In [4]:
 # returns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.

import numpy as np 
aa= np.array([1,2])
ss=np.array([1,2,3,4])
print (aa)
print(ss)
print (aa.shape)
print(ss.shape)

[1 2]
[1 2 3 4]
(2,)
(4,)


In [11]:
import numpy as np
yesrr = np.array([1,2,3,4,5,6] , ndmin = 5 ) # verify  the last dimension has 6 values in array list 
print(rr)
print (' shape of array ' , rr.shape )

[[[[[1 2 3 4 5 6]]]]]
 shape of array  (1, 1, 1, 1, 6)


In [2]:
# reshaping  1-D array to 2-D array 
#Convert the following 1-D array with 12 elements into a 2-D array
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 ])

newarr = arr.reshape(4,3)
print (newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [1]:
##Convert the following 1-D array with 16 elements into a 2-D array

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,13,14,15,16 ])

newarr = arr.reshape(4,4)
print (newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [7]:
#Reshape From 1-D to 3-D
# Convert the following 1-D array with 12 elements into a 3-D array.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) 
print (arr)
print ()

newarr = arr.reshape(2, 3, 2)

print(newarr)
print (newarr.dtype)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
int64


In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 ,13,14,15,16])

newarr = arr.reshape(4, 2, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 ,13,14,15,16,17,18,19,20])

newarr = arr.reshape(4, 5, 1)

print(newarr)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]

 [[11]
  [12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]
  [20]]]


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 ,13,14,15,16 ,17,18,19,20,21,22,23,24,] , ndmin = 5)

newarr = arr.reshape(6,2,2)
print ( newarr) 
print (newarr.dtype)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]

 [[21 22]
  [23 24]]]
int64


numpy array  iterating :>>>> 
 1. Iterating means going through elements one by one.
 2. this is deals with the multidimensional  array. we can do this basic for loop
 3. if we itrate on a 1-d array it will go throw each elelment one by one
 4. 

In [11]:
#1-D array
import numpy  as np 
aa= np.array([1,3,24,5,8])
for x in aa:
    print (x)
print (aa)

1
3
24
5
8
[ 1  3 24  5  8]


In [8]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6],[5,4,3]])

for x in arr:
  print(x)
  print () 
  print (arr)

[1 2 3]

[[1 2 3]
 [4 5 6]
 [5 4 3]]
[4 5 6]

[[1 2 3]
 [4 5 6]
 [5 4 3]]
[5 4 3]

[[1 2 3]
 [4 5 6]
 [5 4 3]]


In [5]:
import numpy as np

arr = np.array([[[0,0,0],[1, 2, 3], [4, 5, 6]]])

for x in arr:
  for y in x:
    print(y)
    print (arr)
print (arr.shape)

[0 0 0]
[[[0 0 0]
  [1 2 3]
  [4 5 6]]]
[1 2 3]
[[[0 0 0]
  [1 2 3]
  [4 5 6]]]
[4 5 6]
[[[0 0 0]
  [1 2 3]
  [4 5 6]]]
(1, 3, 3)


In [15]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] , ndmin = 5)
print (arr) 
print(x)
for x  in arr:
    print (arr.dtype)
    print(arr.shape)


[[[[[ 1  2  3]
    [ 4  5  6]]

   [[ 7  8  9]
    [10 11 12]]]]]
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]
int64
(1, 1, 2, 2, 3)


In [26]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)


[1 2 3]
[4 5 6]


In [27]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print (arr)

[[1 2 3]
 [4 5 6]]


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4])
for x in arr:
    print(x)
    print (arr)

1
[1 2 3 4]
2
[1 2 3 4]
3
[1 2 3 4]
4
[1 2 3 4]
